# Conclusion

Through our exploration of binge drinking behaviors across the country we have gained many insights. We know that binge drinking trends are normally distributed. We also know that some regions in the US have different behaviors than others, specifically that the Midwest consistently displays higher than average binge drinking prevalence rates than other regions. When exploring age and population, there does not seem to be any type of correlation between them and binge drinking. However, we only had access to the average age of each state which doesn't necessarily imply a lack of correlation between age in general and drinking, which would require a completely different data sets. Similarly, population was used as a proxy for the size and livelihood of the states which isn't necessarily true. In the future, this project could be improved with the incorporation of several different variables such as climate and amount of colleges/bars in the area, and the ability to explore binge drinking habits for individual age groups as well as cities/regions.
