# Introduction

Welcome to our project about visualizing binge drinking in the united states. We chose this project because binge drinking is often portrayed as a regular occurrence in the life of Americans (especially grad students) and we thought that it would be interesting if we could visualize binge drinking trends across the country. 

According to the CDC, Binge drinking is defined as consuming 5 or more drinks on an occasion for men and 4 or more drinks on an occasion for women. Officially, it's consuming alcohol that brings a person's blood alcohol level to over 0.08%, which averages to the amount stated above. Binge drinking is not uniform across age groups, income levels, geographical location, etc. 

Some areas in the Untied States have reputations for higher rates of binge drinking, like around college campuses. Other regions are known as living healthier lifestyles where drinking is not as prevalent. A state like Utah has a large population of people that do not drink alcohol for religious regions. While Tennessee is known for having their own type of alcohol (Whiskey). Some areas in the US are known to have specific repuations and it is interesting to note how these reputations correspond to actual binge drinking rates. 

We would like to answer questions such as in which regions is binge drinking more prevalent. This might provide insight over cultural differences in approaches to drinking across states/regions. Another similar question would be does lower population increase likelihood of binge drinking. This is an interesting question because it is a commonly held opinion that binge drinking is more common in small towns because "there is nothing to do". Finally we could also find temperature data for these states and see if there's any variation in binge drinking tendencies based on climate information. 

